menobass/hivesnaps

- app/ProfileScreen.tsx
- Fixed checkFollowStatus() function to properly query follow relationships
- Changed API parameters from [currentUsername, username, 'blog', 1] to [currentUsername, '', 'blog', 1000]
- Now fetches all users that current user follows, then searches for target username
- Applied same fix to mute status detection for consistency
- Added comprehensive debug logging for follow/mute status checks
- Enhanced error handling with fallback states
- Resolves issue where follow button incorrectly showed 'Follow' after user had already followed someone
The bug was caused by incorrect API parameter order - the original call was trying to get followers starting from a specific user instead of getting all users that the current user follows.
> fix: Correct follow status detection API logic in ProfileScreen

- app/ConversationScreen.tsx
Fix keyboard covering the edit modal in Conversation Screen
> fix: edit modal covered by keyboard

- app/NotificationsScreen.tsx
- utils/notifications.ts
- Make follower notifications clickable and navigate to user profile
- Fix regex pattern in notifications parser to handle 'followed you' message format
- Add fallback to extract username from URL field when regex fails
- Update TouchableOpacity disabled logic to enable follow notifications
- Navigate to ProfileScreen with follower's username when notification is tapped
Resolves: Users can now tap on follower notifications to view the profile of the person who followed them, improving user engagement and discoverability.
> feat: add clickable follower notifications

- test/test-username-regex.js
- utils/notifications.ts
Fixed regex patterns in utils/notifications.ts to support Hive usernames containing dots
Changed \w+ patterns to [a-z0-9.-]+ to match valid Hive username format
Resolves issue where notifications from users like @atma.love were not clickable
Added test file to verify regex patterns work correctly with dot-containing usernames
Before: @atma.love -> extracted as 'atma' (broken)
After: @atma.love -> extracted as 'atma.love' (correct)
Patterns updated:
- Vote notifications: /@([a-z0-9.-]+) voted on your post/
- Reply notifications: /@([a-z0-9.-]+) replied to your/
- Reblog notifications: /@([a-z0-9.-]+) reblogged your/
- Follow notifications: /@([a-z0-9.-]+) (?:followed|started following) you/
- Mention notifications: /@([a-z0-9.-]+) mentioned you/
- URL parsing: …
> fix: Handle usernames with dots in notification parsing

- app/ConversationScreen.tsx
- app/DiscoveryScreen.tsx
- app/FeedScreen.tsx
- app/ProfileScreen.tsx
- app/components/ContentModal.tsx
- app/components/Snap.tsx
- hooks/useEdit.ts
- test/image-extraction-test.js
- utils/extractImageInfo.ts
fix: preserve images when editing snaps and replies
- Add extractImageInfo utility to properly handle image extraction and preservation
- Update useEdit hook to preserve existing images during edit modal opening
- Enhance ContentModal to display image information (URL and markdown) in edit mode
- Add comprehensive test suite for image extraction functionality
- Fix issue where editing snaps/replies with images would delete the photo
The fix ensures that when users edit content containing images, the images are:
- Preserved in the edit modal instead of being lost
- Displayed with technical information (URL and markdown syntax)
- Properly handled for both markdown and HTML image formats
- Testable with robust test coverage
> Hiv 2/images lost when editing snap

- app/FeedScreen.tsx
- components/SmallButton.tsx
- components/StaticContentModal.tsx
- hooks/useResourceCredits.ts
- styles/FeedScreenStyles.ts
NEW FEATURES:
- Added Resource Credits display next to Voting Power in top bar
- Side-by-side VP/RC layout with clean separator (VP: 85.2% | RC: 92.1%)
- Educational RC modal explaining 'digital fuel' concept
- Username truncation for better mobile layout (8 chars + '...')
TECHNICAL IMPLEMENTATION:
- Created useResourceCredits hook following useVotingPower pattern
- Integrated official Hive rc_api.find_rc_accounts API
- Proper TypeScript interfaces matching Hive API spec
- String-to-number conversion for large RC values
- Error handling with graceful fallbacks
UX/ACCESSIBILITY IMPROVEMENTS:
- Both VP and RC modals now fully scrollable (maxHeight: 80%)
- Touch-friendly buttons with proper hit slop areas
- Screen reader support with accessibility labels
- Responsive design for various …
> feat: implement Resource Credits (RC) display alongside Voting Power

- app/ComposeScreen.tsx
- app/ConversationScreen.tsx
- app/DiscoveryScreen.tsx
- app/FeedScreen.tsx
- app/ProfileScreen.tsx
- app/components/Snap.tsx
- Add resnap icon (retweet) to Snap component action bar
- Implement onResnapPress handler across all screens (Feed, Conversation, Discovery, Profile)
- Navigate to ComposeScreen with pre-filled Hive post URL
- Auto-focus text input and position cursor below URL for immediate commenting
- Generate hive.blog URLs in format: https://hive.blog/@author/permlink
- Handle URL parameters safely with proper TypeScript types
- Maintain consistent styling and accessibility labels
Allows users to easily share and comment on existing snaps by clicking the resnap icon, providing a seamless Twitter-like resharing experience.
> feat: implement resnap functionality with auto-focus UX

- app/components/Snap.tsx
- components/HivePostPreview.tsx
- utils/extractHivePostInfo.ts
- utils/postTypeDetector.ts
fix: make snap detection inclusive for external Hive posts
- Add content characteristics detection for short-form posts without titles
- Implement universal resnapping support for any valid Hive post
- Allow resnapping from PeakD, Ecency, Hive.blog and other frontends
- Maintain backward compatibility with native HiveSnaps detection
- Remove restrictive app-specific metadata requirements for resnapping
Fixes issue where users couldn't resnap posts created outside HiveSnaps app.
Now any Hive post with valid author/permlink can be resnapped regardless
of which frontend was used to create it.
> Hiv 8/resnap bug

- lib/notificationService.ts
- Replace SecureStore with AsyncStorage for notification history
- SecureStore has 2048-byte limit, AsyncStorage has no practical limit
- Notification IDs are non-sensitive data, appropriate for AsyncStorage
- Keeps existing safeguard of max 1000 notification IDs
- Prevents 'Value being stored in SecureStore is larger than 2048 bytes' warnings
- No impact on login credentials (still in SecureStore)
Fixes storage size warnings that could cause app crashes
> Fix notification storage size limit by switching to AsyncStorage

- utils/notifications.ts
- Reply notifications from Hive blockchain use type 'reply_comment'
- Previous filtering only handled 'reply' type
- Now both 'reply' and 'reply_comment' are filtered by replies setting
- Fixes issue where reply notifications ignored disabled setting
Resolves notification filtering inconsistency
> fix: Add support for reply_comment notification type in filtering

- app/ConversationScreen.tsx
- app/components/Snap.tsx
- components/__tests__/__snapshots__/StyledText-test.js.snap
- package-lock.json
- package.json
- utils/rawImageUrls.ts
Summary Re-implements and expands PR #57 on latest main. Centralizes raw image URL detection/removal in utils and wires it into Snap and Conversation to avoid URL blobs while still rendering images cleanly.
Changes
[rawImageUrls.ts]
extractRawImageUrls: detects direct and Hive proxy “double” image URLs (with queries), ignores markdown images, strips trailing punctuation, fresh regex per call, documented.
removeRawImageUrls: removes raw image URLs from text while preserving newlines/paragraph spacing; handles “(URL)” → “(” case.
[Snap.tsx]
Renders images from raw URLs and removes them from text before Markdown/HTML to prevent duplicates.
[ConversationScreen.tsx]
Mirrors the same behavior for snap header and replies.
Tests
[rawImageUrls.test.ts] ensures extraction and whitespace/newline …
>  Reapply: robust raw image URL handling and text cleanup (Snap + Conversation)

- utils/extractHivePostInfo.ts
Urls with double "--" would get ignored by our Preview Parser
> Allow consecutive hyphens in permlink validation 

- app/(tabs)/index.tsx
- Changed URL from https://signup.hive.io/ to https://hive.io/
- Updated text from 'Don't have a Hive account?' to 'Learn more at hive.io'
- Updated accessibility label to 'Learn more about Hive'
- Renamed handleSignUpPress to handleLearnMorePress for clarity
- Updated comment from 'Signup link' to 'Learn more link'
This change addresses App Store compliance requirements by directing users to educational content about Hive rather than direct account creation, avoiding issues with account deletion policies while maintaining user value.
> fix: Update Hive link for App Store compliance

- README.md
- components/TermsOfServiceModal.tsx
- constants/TermsOfService.ts
- Remove 'App Store Compliance' banner for cleaner UI
- Fix iOS double-alert issue when declining terms
- Simplify decline flow to single alert on iOS
- Remove temporary debug button
Changes:
- TermsOfServiceModal.tsx: Remove compliance banner, simplify decline handler
- Clean up debug code from FeedScreen.tsx
> Fix: Improve Terms of Service modal UX

- app/ConversationScreen.tsx
- app/HivePostScreen.tsx
- app/components/Snap.tsx
- Add 'Go to Profile' as first option in ActionSheet menu in Snap component
- Enable navigation to user profiles from any Snap context
- Added onUserPress handlers to ConversationScreen (both main post and replies)
- Added onUserPress handler to HivePostScreen for comment navigation
- Excluded ProfileScreen since all snaps belong to profile owner (redundant)
Features:
ConversationScreen: Navigate to commenter profiles from replies
HivePostScreen: Navigate to commenter profiles from comments
DiscoveryScreen: Navigate to author profiles (already had onUserPress)
FeedScreen: Navigate to author profiles (already had onUserPress)
This provides consistent access to user profiles across all contexts where users interact with content from multiple authors.
> Add 'Go to Profile' option to Snap three-dots menu

- app/FeedScreen.tsx
- hooks/useFeedData.ts
- hooks/useFollowManagement.ts
- store/context.tsx
- store/types.ts
- store/userSlice.ts
- Add memoized following list filter using Set for O(1) author lookups vs O(n) array.includes()
- Add memoized user posts filter to avoid recalculation on filter changes
- Add memoized filtered snaps calculation to prevent expensive re-filtering on each render
- Add memoized avatar enrichment to avoid re-processing when filter results unchanged
- Optimize setFilter function to use memoized results and skip duplicate filter calls
- Use setTimeout for non-blocking fetchSnaps calls in setFilter
- Return memoized enriched snaps when available for better performance
Performance impact: Significantly reduces CPU usage during filter changes, especially for users with large following lists or when switching to 'following' filter frequently.
> feat: optimize follow list filtering with comprehensive memoization

- app/HivePostScreen.tsx
- Fixed JSX compilation error caused by duplicate onUserPress props
- Snap component now has single onUserPress handler for profile navigation
- Critical hotfix needed for app compilation
This error was likely introduced during recent PR merges and breaks JSX compilation.
> Fix: Remove duplicate onUserPress attribute in HivePostScreen

- app/components/Snap.tsx
- hooks/useNotifications.ts
- Added muted user filtering to useNotifications hook
- Uses existing useMutedList() shared state (same pattern as FeedScreen)
- Filters out notifications where actionUser is in the combined muted list
- Combined list includes personal mutes + global blacklist from menosoft.xyz
- Fixes harassment issue where muted users still send notifications
- Preserves notifications without actionUser (system notifications)
> Fix: Hide notifications from muted users

- app/components/Snap.tsx
- Add Clipboard import from react-native
- Add handleCopyToClipboard function that copies cleanTextBody to clipboard
- Add 'Copy to Clipboard' option to ActionSheet menu between Profile and Report
- Show confirmation alert when content is copied
- Simple 15-line implementation following existing patterns
Allows users to easily copy snap text content for sharing or reference
> feat: add copy to clipboard option to snap three-dot menu

- app/components/Preview.tsx
- app/screens/ComposeScreen.tsx
- Add preview button to markdown toolbar with eye icon
- Create preview modal that reuses Snap component
- Implement createPreviewSnapData() to generate mock SnapData
- Preview disabled when no content (text, images, or GIFs)
- Modal shows exactly how the snap will look when posted
> feat: add compose preview functionality
